language: python

python: 3.6

sudo: false
cache:
  directories:
    - "$HOME/.cache/pip"

install: pip install -r _build/.requirements.txt

script: make -C _build SPHINXOPTS=-nW html

notifications:
  webhooks:
      secure: "Pp9jm0HNQjQTIJk7c3tQswMHeAJezPh884JdFL4bpFWUGn2XKIzcazbJtFEGHen6AZrNRRK72rCGMXGqz0hErsf1LTL0F/DfKB64ULhZgReZsKOuMaMCKY3qA8rn9X8eiosVGqftxutfcmyf7E0u6Hry1zjjPGRACPnrbh/9FzGDzUc6Jz1JypmPLJtcEXOavXzCs0NQMq6qHSFbVUDdMqadtkYe0vxsx6AWdV+5tq7M5NclA/EM5ySwEm67+Rw3oXGABK9W/9tsCFrp1RpbE/diZmbIoYkCL0YTv6Rua/hz921HcVpvHak6/CGUDdkaZtBb7khFwuuRL0/pN1c0Iz7mVXSUMsSIP5N/YoO5ZDTIFYPpdo9+Hya8QZlOaF9hJcvbvKQKJh0bJ9gZdyxBM/BMW+5Al27tm6n5YlDXg/xsa2aZ6yEdjfuVyf/6SlC8aNCXvzZKRKgvdS9+LpshSr12z0A/n2gW15sp4+bHT6VTCdlYOI84oztLl/fWoIOjdssg6kvUC0EVDtHZCcsu72oKkxe5o/43LGzvrHmIfGnEYcSDC7ZiD95cR4fWQryIKVC3KBdSGTIRdO79xyjKyIHmaQPxjgN8OuQGqpwyVx8df2LB4byT3Cey2FYGx0kGjlWCld1fqriEcXW5OzYsnSFOVb0s8v4pL8pJy6Ik/Ho="